# Copyright 2017 Intel Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../mk
IMAGENAME = gtp-u-boom
EXECUTABLES = gtp-u-boom

debug:
	$(MAKE) NFF_GO_DEBUG=y


include $(PATH_TO_MK)/intermediate.mk
include $(PATH_TO_MK)/leaf.mk
